services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - path: .env
        required: true
    volumes:
      - .env:/app/.env
    depends_on:
      - db

  postgres:
    image: postgres:16
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    env_file:
      - path: .env
        required: true
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_db
    ports:
      - "5432:5432"